<?php $this->headTitle('User Dashboard') ?>
<?php $this->headScript()->appendFile('/js/jquery.textareaCounter.plugin.js'); ?>

<?php $this->jquery()->onloadCaptureStart();?>

    function loadContent() {    
        $('#tag-list-container').load('/user/xhr-get-tag-list');
        $('#activityStream').load('/user/xhr-get-activity-stream');
    };
    loadContent();

    $('#tag').live('keyup', function() {
        var value = $(this).val();
        value = value.toLowerCase();
        value = value.replace(/[^a-z0-9]/, '');
        $(this).val(value);
        return false;
    });
    
    $('.delete-tag').live('click', function() {
        var tag = $(this).attr('id').replace(/delete\-/, '');
        var confirm = $('<div id="delete-message">'
            + '<p>Are you sure you want to delete the tag ' + tag + '</p>'
            + '<button id="confirm-delete">Delete</button>'
            + '<button id="cancel-delete">Cancel</button>'
            + '</div>');
            confirm.dialog();
        
        $('#cancel-delete').live('click', function() {
            confirm.dialog('close');
        });
        
        $('#confirm-delete').live('click', function() {
            $.post('/user/xhr-delete-tag/tag/' + tag, {});        
            loadContent();
            confirm.dialog('close');
            
        });
        return false;
        
    });
    
    $('.tag').live('click', function(event) {
        var href = $(this).attr('href');
        var modal = $('<div id="form-container"/>').load(href);
       
        modal.dialog();
        
        $('#tagdata').live('submit', function() {   
            $.post(
                '/user/xhr-tag', 
                { tag : $('#tag').val(), tag_content : $('#tag_content').val() }, 
                function(data) {
                    if (data === 'success') {
                        loadContent();
                        modal.dialog('close');
                        return;
                    }
                   
                    $('#form-container').html(data);


                }
            );
            return false; 
        });
        return false;
    });
<?php $this->jquery()->onloadCaptureEnd();?>
<div id="dashboard">
    <h2>Your dashboard</h2>
    <p>
        Welcome to your user dashboard, here you can view all the activity on your 
        account and add, remove and edit tags.
    </p>

    <div id='tag-list-container'>
    
    
    </div>

    <div id="activityStream">

    
    </div>
</div>
<div style="clear:both"/>






