<h1 class="signup">Need some help?</h1>
<p class="signup">
    We hope we've created an easy to use service, but in the event we 
    haven't here is some help. Each of the below are things you can send
    to <span class="smsafenumber">447781480565</span>. You don't need to use the '{' and '}'.
</p>
<h3>Retrieve a tag:</h3>
<p>
   {password} {tag} (or {password} get {tag})
</p>
<h3>Add a tag:</h3>
<p>
    {password} add {tag} {content}
</p>

<h3>Update a tag:</h3>
<p>
    {password} update {tag} {content}
</p>
<h3>Delete a tag:</h3>
<p>
    {password} delete {tag} {content}
</p>
<h3>List all your tags (up to 140 chars):</h3>
<p>
    {password} listtags
</p>
<h3>Get some help:</h3>
<p>
    {password} help
</p>
<?= $this->form; ?>