<?php $this->headTitle('Data Entry'); ?>
<?php $this->headScript()->appendFile('/js/jquery.textareaCounter.plugin.js'); ?>

<?php $this->jquery()->onloadCaptureStart();?>
$('#tag_content').textareaCount({
				'maxCharacterSize': 140,
                'displayFormat' : '#left characters left'
});
    
$('#tag').keyup(function() {
    var value = $(this).val();
    value = value.toLowerCase();
    value = value.replace(/[^a-z0-9]/, '');
    $(this).val(value);
    return false;
});

<?php $this->jquery()->onloadCaptureEnd();?>

<div id="ct_left">
    <?= $this->form; ?>
</div>
<div id="ct_right">

</div>