<!DOCTYPE html>
<html>
	<head>
		<?= $this->headMeta(); ?>
			
		<?= $this->headTitle(); ?>
		
		<link href="/css/style.css" rel="stylesheet" type="text/css" />
		<?= $this->headLink(); ?>
	</head>
	
	<body>
	    <div id="header">
	        <h1>Super Awesome App</h1>
    	    <div id="navigation">
        	    <ul>
        	        <li><a href="/">Home</a></li>
        	        <li><a href="/index/inbox">Inbox</a></li>
        	        <li><a href="/index/send">Send Message</a></li>
        	    </ul>
    	    </div>
    	</div>
		<?= $this->layout()->content ?>			

		<?= $this->jQuery() ?>
		<?= $this->headScript() ?> 

	</body>
</html>
