<div id="ct_left">
    <img src="/images/cat_polaroid.jpg" align="right" class="bodyimage" />
    <h2>ZOMG! What's my my thing again?</h2>
    <p>

        We've all done it right? Stuck on the continent, mobile provider
        charging huge amounts of money for roaming data and you've 
        forgotten the pin number for your holiday credit card! You want
        to buy that multi-colored sombrero, or the bull shaped clock, or
        the services of a young woman...
    </p>
    <h2>Never fear, <span class="brand_name">SMSafe</span> is here!</h2>
    <p>
       Simply sign up to <span class="brand_name">SMSafe</span> and all your
       "forgetting shit like a moron" woes go away! Securely* store your pin number, bank
       details, passport number, driving licence details, medical details or, 
       in fact, anything in <span class="brand_name">SMSafe</span> and
       you'll instantly have access to it all, even without roaming data!
    </p>
    <p>
       We'll send you any of your details when you text our 
       <span class="brand_name">SMSafe</span> bot your password and the item
       you want it to retrieve and we'll SMS it to you, wherever you are!
    </p>
    <p>
       So, <a href="/signup">sign up</a> today and start benefiting by getting 
       your shit when you need it most - even with the power of the internets! 
    </p>
    <p class="small">
        *We store it securely, there are no guarantees your network provider
        treats your SMS's as securely as we do!
    </p>
</div>
<? if (!$this->isLoggedIn) : ?>
<div id="ct_right">
    <span class="box_title"><h3>Signup Here!</h3></span>
    <p>
        Enter your mobile number and hit 'Signup!', we'll do the rest!
    </p>
    <?= $this->form; ?>
    <span class="box_title"><h3>Login!</h3></span>
    <?= $this->loginForm; ?>
</div>
<? endif; ?>