<div class="signup">
    <h1 class="signup">Step 3: A password</h1>
    <p class="signup">

        Thanks! Your account is now verified, you need to do one more thing and
        that is go provide us with a password.
    </p>
    <p class="signup">
        Password: between <strong>six</strong> and <strong>twelve</strong> 
        letters and numbers.
    </p>
    </p>
    <?= $this->form; ?>
</div>